config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :creatures
  resources :tags

end

app/models/creature.rb
class Creature < ActiveRecord::Base

  has_and_belongs_to_many :tags

end

app/models/creatures_tags.rb
class CreaturesTags < ActiveRecord::Base
  belongs_to :creature
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_and_belongs_to_many :creatures

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/creatures_controller.rb
require 'flickraw'

class CreaturesController < ApplicationController

  def index
    @creatures = Creature.all
  end

  def new
    @creature = Creature.new
    @tags = Tag.all
  end

  def create

    # render :json => params

    @creature = Creature.create(creature_params)

    params['creature']['tag_ids'].each do |tag_id|
      @creature.tags << Tag.find(tag_id) unless tag_id.blank?
    end
    redirect_to @creature
  end

  def show
    # Set up the FlickRaw gem
    FlickRaw.api_key=ENV["FLICKR_API_KEY"]
    FlickRaw.shared_secret=ENV["FLICKR_API_SECRET"]

    # Find the current creature
    @creature = Creature.find(params[:id])

    # Retrieve a list of images that are relevant to the creature name
    list = flickr.photos.search :text => @creature.name, :sort => "relevance"

    # The list of images returns sorted by relevant
    # Retrieve the 3 most relevant public photos
    photolist = []
    i = 0
    until photolist.length == 3 do
      photolist << list[i] if list[i].ispublic
      i += 1
    end

    # For each photo retrieve the small version of the image
    @photos = []
    photolist.each do |photo|
      sizes = flickr.photos.getSizes :photo_id => photo.id
      # The fourth object is always the small picture
      @photos << sizes[3]
    end
  end

  def edit
    @creature = Creature.find(params[:id])
    @tags = Tag.all
  end

  def update
    @creature = Creature.find(params[:id])
    @creature.update!(creature_params)

    params['creature']['tag_ids'].each do |tag_id|
      @creature.tags << Tag.find(tag_id) unless tag_id.blank?
    end

    redirect_to @creature
  end

  def destroy
    Creature.find(params[:id]).destroy
    redirect_to creatures_path
  end

  private

  def creature_params
    params.require(:creature).permit(:name,:description)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def create

    @tag = Tag.create(tag_params)
    redirect_to :tags

  end

  def show
    @tag = Tag.find(params[:id])
    @creatures = @tag.creatures
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    @tag.update!(creature_params)
  end

  def destroy
    @tag = Tag.find(params[:id])
    if @tag.creatures.length == 0
      @tag.destroy
      redirect_to :tags
    else
      # flash[:danger] = "Cannot delete this tag because there is/are #{@tag.creatures.length} creature(s) using it."
      @tag.creatures.each do |c|
        c.tags.delete(@tag)
      end
      @tag.destroy
      redirect_to :tags
    end
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/creatures/edit.html.erb
<h1>Edit This Creature</h1>

<div class="row">
  <div class="col-xs-12 col-sm-4 col-sm-offset-4">
    <%= render "layouts/creatures_tags_form" %>
  </div>
</div>

app/views/creatures/index.html.erb
<h1>Creatures List</h1>

<div class="row">
  <div class="col-xs-12 col-sm-12">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @creatures.each do |c| %>
          <tr>
            <td><%= link_to c.name, c %></td>
            <td>
              <%= link_to '', edit_creature_path(id: c[:id]), :class => "btn btn-success glyphicon glyphicon-pencil" %>
              <%= link_to '', c, :method => "delete", :class => "btn btn-danger glyphicon glyphicon-remove" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/creatures/new.html.erb
<h1>Create a Creature</h1>

<div class="row">
  <div class="col-xs-12 col-sm-4 col-sm-offset-4">
    <%= render "layouts/creatures_tags_form" %>
  </div>
</div>

app/views/creatures/show.html.erb
<h1>Show page for a Creature</h1>

<div class="row">
  <div class="col-xs-12 col-sm-12">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @creature.name %></td>
          <td><%= @creature.description %></td>
          <td>
            <%= link_to '', edit_creature_path, :class => "btn btn-success glyphicon glyphicon-pencil" %>
            <%= link_to '', @creature, :method => "delete", :class => "btn btn-danger glyphicon glyphicon-remove" %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-xs-4 col-sm-4">
    <img src="<%=@photos[0].source%>" class="img-responsive" alt="Image">
  </div>
  <div class="col-xs-4 col-sm-4">
    <img src="<%=@photos[1].source%>" class="img-responsive" alt="Image">
  </div>
  <div class="col-xs-4 col-sm-4">
    <img src="<%=@photos[2].source%>" class="img-responsive" alt="Image">
  </div>
</div>

app/views/home/index.html.erb
<h1>Welcome to my Bog App<small>You have been warned</small></h1>

app/views/layouts/_creatures_tags_form.html.erb
<%= bootstrap_form_for @creature do |f| %>
<%= f.text_field :name, :placeholder => "Enter a name" %>
<%= f.text_field :description, :placeholder => "Enter a description" %>
<%= f.collection_check_boxes :tag_ids, @tags, :id, :name %>
<%= f.primary %>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |k,v| %>
  <div class="alert alert-<%= k %>">
    <%= v %>
  </div>
<% end %>

app/views/layouts/_tags_form.html.erb
<%= bootstrap_form_for @tag do |f| %>
<%= f.text_field :name, :placeholder => "Enter a tag name" %>
<%= f.primary %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Da Bog</title>

  <!-- Boostrap CSS -->
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
  <!-- Local CSS -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
  <!-- Boostrap JS -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <!-- Local JS -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">


    <nav class="navbar navbar-default" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Da Bog", root_path, :class => "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <!-- <ul class="nav navbar-nav">
          <li class="active"><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
        </ul>
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form> -->
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Tags", tags_path %></li>
          <li><%= link_to "Add Tag", new_tag_path %></li>
          <li><%= link_to "Creatures", creatures_path %></li>
          <li><%= link_to "Add Creature", new_creature_path %></li>

          <!-- <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li> -->
        </ul>
      </div><!-- /.navbar-collapse -->
    </nav>

    <%= render "layouts/flash" %>

    <%= yield %>

  </div>

</body>
</html>

app/views/tags/edit.html.erb
<h1>Edit This Tag</h1>

<div class="row">
  <div class="col-xs-12 col-sm-4 col-sm-offset-4">
    <%= render "layouts/tags_form" %>
  </div>
</div>

app/views/tags/index.html.erb
<h1>Tags List</h1>

<div class="row">
  <div class="col-xs-12 col-sm-12">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @tags.each do |t| %>
          <tr>
            <td><%= link_to t.name, t %></td>
            <td>
              <%= link_to '', edit_tag_path(id: t[:id]), :class => "btn btn-success glyphicon glyphicon-pencil" %>
              <% if t.creatures.length > 0 %>
                <%= link_to '', t, :method => "delete", data: { confirm: "There are #{t.creatures.length} creatures using this tag. Are you sure you want to delete this tag?" }, :class => "btn btn-danger glyphicon glyphicon-remove" %>
              <% else %>
                <%= link_to '', t, :method => "delete", :class => "btn btn-danger glyphicon glyphicon-remove" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tags/new.html.erb
<h1>Create Tag</h1>

<div class="row">
  <div class="col-xs-12 col-sm-4 col-sm-offset-4">
    <%= render "layouts/tags_form" %>
  </div>
</div>

app/views/tags/show.html.erb
<h1><small>Creatures Tagged: </small><%= @tag.name %></h1>

<div class="row">
  <div class="col-xs-12 col-sm-12">
    <table class="table">
      <thead>
        <tr>
          <th>Creature</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        <% @creatures.each do |c| %>
          <tr>
            <td><%= link_to c.name, c %></td>
            <td><%= c.description %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>